import React from "react";

type Props = {};

export const metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <main className="py-12  lg:px-48 sm:px-24 px-12">{children}</main>;
}
