import React from "react";

type Props = {};

export const metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
}
